name: Build and deploy container app to Azure Web App - hamza3003

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_535af26a8bd44f43b60297dc456d9adb }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c43cd6092fe04b0c929c7f3b4d4db008 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_535af26a8bd44f43b60297dc456d9adb }}/appsvc/wordpress-alpine-php:${{ github.sha }}
        context: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hamza3003'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_10be37e258de418ebdbe8b68bc08d420 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_535af26a8bd44f43b60297dc456d9adb }}/appsvc/wordpress-alpine-php:${{ github.sha }}
